name: Java to GCP Workflow

on:
  push:

jobs:
  Java-Workflow:
    uses: ErnestoAzziorri2021/pruebaDevOpsInfra/.github/workflows/Java-Workflow.yml@main
    with:
      service-name: products
      sonar-project-key: DevOpsORT-proyecto_products-service
    secrets: inherit